## Theory1

In [1]:
import numpy as np

x = np.array([1,2,3])
W = np.array([[1,2],[3,4],[5,6]])
b = np.array([-1, 2])

print(x)
print(x.shape)


[1 2 3]
(3,)


In [2]:
print(W)
print(W.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [3]:
print(b)
print(b.shape)

[-1  2]
(2,)


In [4]:
dot = np.dot(x, W)

In [5]:
print(dot)

[22 28]


In [6]:
print(dot + b)

[21 30]


## Theory2

In [7]:
h = np.array([10, -1])

In [8]:
print(h)

[10 -1]


In [9]:
## if the data was processed by the Linear Layer

def linear(h):
    return h

In [10]:
print(linear(h))

[10 -1]


In [11]:
## if the data was processed by the ReLU Layer

def ReLU(h):
    return np.maximum(0, h)

In [12]:
print(ReLU(h))

[10  0]


In [13]:
## if he data was processed by the sigmoid Layer

def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [14]:
print(sigmoid(h))

[0.9999546  0.26894142]


In [15]:
## if the data was processed by hyperbolic tanH

def tanH(h):
    return np.tanh(h)

In [16]:
print(tanH(h))

[ 1.         -0.76159416]


In [17]:
## if the data was processed by the softmax Layer

def softmax(h):
    exps = np.exp(h - np.max(h))
    return exps / np.sum(exps)

In [18]:
print(softmax(h))

[9.99983299e-01 1.67014218e-05]


In [19]:
X = np.array([[1,2,3,4],[5,6,7,8]])

W = np.array([[1,2],[2,0],[1,1],[-1,4]])

b = np.array([1,2])

In [20]:
def forward(X, W, b):
    return np.dot(X, W) + b

In [21]:
print(forward(X, W, b))

[[ 5 23]
 [17 51]]


In [22]:
import pandas as pd

df = pd.read_csv('../data/mcpd_augmented.csv')

In [23]:
df.head()

age  sex     bmi  children  smoker  isSouthwest  isSoutheast  isNorthwest  \
0   19    0  27.900         0       1            1            0            0   
1   18    1  33.770         1       0            0            1            0   
2   28    1  33.000         3       0            0            1            0   
3   33    1  22.705         0       0            0            0            1   
4   32    1  28.880         0       0            0            0            1   

   isNortheast  
0            0  
1            0  
2            0  
3            0  
4            0

In [24]:
data = df.values

In [25]:
data.shape

(1338, 9)

In [29]:
import layers as ly

inputLayer = ly.inputLayer(data)
dataOut = inputLayer.forward(data)
fullyConnectedLayer = ly.fullyConnectedLayer(9, 2)
dataOut1 = fullyConnectedLayer.forward(dataOut)
logisticLayer = ly.logisticSigmoidLayer(dataOut1)
dataOut2 = logisticLayer.forward(dataOut1)

print(dataOut2)


[[0.49998449 0.49997771]
 [0.499983   0.4999692 ]
 [0.50000033 0.49996783]
 ...
 [0.49997927 0.4999657 ]
 [0.49998961 0.49998034]
 [0.5000498  0.49995934]]


In [33]:
inputLayer = ly.inputLayer(data)
dataOut = inputLayer.forward(data)
fullyConnectedLayer = ly.fullyConnectedLayer(df.size[1], 2)
dataOut1 = fullyConnectedLayer.forward(dataOut)
logisticLayer = ly.logisticSigmoidLayer(dataOut1)
dataOut2 = logisticLayer.forward(dataOut1)

print(dataOut2)

[[0.4999547  0.5000013 ]
 [0.49994839 0.50000672]
 [0.49996463 0.49999093]
 ...
 [0.49994424 0.50000881]
 [0.49996152 0.49999651]
 [0.50001508 0.49993794]]
