## Theory1

In [47]:
import numpy as np

x = np.array([1,2,3])
W = np.array([[1,2],[3,4],[5,6]])
b = np.array([-1, 2])

print(x)
print(x.shape)


[1 2 3]
(3,)


In [48]:
print(W)
print(W.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [49]:
print(b)
print(b.shape)

[-1  2]
(2,)


In [50]:
dot = np.dot(x, W)

In [51]:
print(dot)

[22 28]


In [54]:
print(dot + b)

[21 30]


## Theory2

In [58]:
h = np.array([10, -1])

In [59]:
print(h)

[10 -1]


In [61]:
## if the data was processed by the Linear Layer

def linear(h):
    return h

In [63]:
print(linear(h))

[10 -1]


In [62]:
## if the data was processed by the ReLU Layer

def ReLU(h):
    return np.maximum(0, h)

In [64]:
print(ReLU(h))

[10  0]


In [67]:
## if he data was processed by the sigmoid Layer

def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [68]:
print(sigmoid(h))

[0.9999546  0.26894142]


In [69]:
## if the data was processed by hyperbolic tanH

def tanH(h):
    return np.tanh(h)

In [70]:
print(tanH(h))

[ 1.         -0.76159416]


In [73]:
## if the data was processed by the softmax Layer

def softmax(h):
    exps = np.exp(h - np.max(h))
    return exps / np.sum(exps)

In [74]:
print(softmax(h))

[9.99983299e-01 1.67014218e-05]


In [79]:
X = np.array([[1,2,3,4],[5,6,7,8]])

W = np.array([[1,2],[2,0],[1,1],[-1,4]])

b = np.array([1,2])

In [80]:
def forward(X, W, b):
    return np.dot(X, W) + b

In [81]:
print(forward(X, W, b))

[[ 5 23]
 [17 51]]


In [83]:
import pandas as pd

df = pd.read_csv('../data/mcpd_augmented.csv')

In [84]:
df.head()

age  sex     bmi  children  smoker  isSouthwest  isSoutheast  isNorthwest  \
0   19    0  27.900         0       1            1            0            0   
1   18    1  33.770         1       0            0            1            0   
2   28    1  33.000         3       0            0            1            0   
3   33    1  22.705         0       0            0            0            1   
4   32    1  28.880         0       0            0            0            1   

   isNortheast  
0            0  
1            0  
2            0  
3            0  
4            0

In [86]:
data = df.values

In [87]:
data.shape

(1338, 9)

In [96]:
import layers as ly

inputLayer = ly.inputLayer(data)

dataOut = inputLayer.forward(data)
fullyConnectedLayer = ly.fullyConnectedLayer(9, 2)
dataOut1 = fullyConnectedLayer.forward(dataOut)
logisticLayer = ly.logisticSigmoidLayer(dataOut1)
dataOut2 = logisticLayer.forward(dataOut1)

print(dataOut2)


[[0.50004846 0.50001924]
 [0.5000569  0.50002914]
 [0.50005483 0.50002319]
 ...
 [0.50006145 0.50003459]
 [0.50004678 0.50001316]
 [0.50005049 0.4999981 ]]


In [98]:
## defining a function to create layers and forward propagate

def forwardPropagate(data, layers):
    dataOut = data
    for layer in layers:
        dataOut = layer.forward(dataOut)
    return dataOut

layers = [inputLayer, fullyConnectedLayer, logisticLayer]

dataOut = forwardPropagate(data, layers)

print(dataOut)

NameError: name 'RelULayer' is not defined