## Theory1

In [145]:
import numpy as np

x = np.array([1,2,3])
W = np.array([[1,2],[3,4],[5,6]])
b = np.array([-1, 2])

print(x)
print(x.shape)


[1 2 3]
(3,)


In [146]:
print(W)
print(W.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [147]:
print(b)
print(b.shape)

[-1  2]
(2,)


In [148]:
dot = np.dot(x, W)

In [149]:
print(dot)

[22 28]


In [150]:
print(dot + b)

[21 30]


## Theory2

In [151]:
h = np.array([10, -1])

In [152]:
print(h)

[10 -1]


In [153]:
## if the data was processed by the Linear Layer

def linear(h):
    return h

In [154]:
print(linear(h))

[10 -1]


In [155]:
## if the data was processed by the ReLU Layer

def ReLU(h):
    return np.maximum(0, h)

In [156]:
print(ReLU(h))

[10  0]


In [157]:
## if he data was processed by the sigmoid Layer

def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [158]:
print(sigmoid(h))

[0.9999546  0.26894142]


In [159]:
## if the data was processed by hyperbolic tanH

def tanH(h):
    return np.tanh(h)

In [160]:
print(tanH(h))

[ 1.         -0.76159416]


In [161]:
## if the data was processed by the softmax Layer

def softmax(h):
    exps = np.exp(h - np.max(h))
    return exps / np.sum(exps)

In [162]:
print(softmax(h))

[9.99983299e-01 1.67014218e-05]


In [163]:
X = np.array([[1,2,3,4],[5,6,7,8]])

W = np.array([[1,2],[2,0],[1,1],[-1,4]])

b = np.array([1,2])

In [164]:
def forward(X, W, b):
    return np.dot(X, W) + b

In [165]:
print(forward(X, W, b))

[[ 5 23]
 [17 51]]


In [166]:
import pandas as pd

df = pd.read_csv('../data/mcpd_augmented.csv')

In [167]:
df.head()

age  sex     bmi  children  smoker  isSouthwest  isSoutheast  isNorthwest  \
0   19    0  27.900         0       1            1            0            0   
1   18    1  33.770         1       0            0            1            0   
2   28    1  33.000         3       0            0            1            0   
3   33    1  22.705         0       0            0            0            1   
4   32    1  28.880         0       0            0            0            1   

   isNortheast  
0            0  
1            0  
2            0  
3            0  
4            0

In [168]:
data = df.values

In [169]:
data.shape

(1338, 9)

In [170]:
import layers as ly

inputLayer = ly.inputLayer(data)
dataOut = inputLayer.forward(data)
fullyConnectedLayer = ly.fullyConnectedLayer(9, 2)
dataOut1 = fullyConnectedLayer.forward(dataOut)
logisticLayer = ly.logisticSigmoidLayer(dataOut1)
dataOut2 = logisticLayer.forward(dataOut1)

print(dataOut2)


[[0.49999498 0.50000729]
 [0.49998279 0.50001424]
 [0.49999052 0.50001594]
 ...
 [0.49997996 0.5000155 ]
 [0.50000024 0.50000673]
 [0.50003083 0.50001016]]
