# Numpy Useful Methods

## Acitivity: two lists is given (a, b), do element-wise addition and multiplication

In [1]:
a = [10, 12, 20]
b = [5, 2, 10]

In [2]:
# instead of element-wise addition, we get list concatenation
a + b

[10, 12, 20, 5, 2, 10]

In [3]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
c = [i+j for i,j in zip(a,b)]

In [ ]:
c

In [ ]:
d = [i*j for i,j in zip(a,b)]
d

In [11]:
import numpy as np

a = np.array([10, 12, 20])
b = np.array([5, 2, 10])

In [12]:
a + b

array([15, 14, 30])

In [13]:
a * b

array([ 50,  24, 200])

## Another useful data manipulation with numpy 

- We have two numpy arrays: `A` , `B`. We want to concatenate them column-wise and row-wise

In [14]:
import numpy as np

A = np.array([[1, 2],[3, 4]])
print('This is Matrix A:')
print(A)
B = np.array([[5, 6],[7, 8]])
print('This is Matrix B:')
print(B)

# column concatination
print('column concatination of A and B:')
print(np.c_[A, B])
# row concatination
print('row concatination of A and B:')
print(np.r_[A, B])

This is Matrix A:
[[1 2]
 [3 4]]
This is Matrix B:
[[5 6]
 [7 8]]
column concatination of A and B:
[[1 2 5 6]
 [3 4 7 8]]
row concatination of A and B:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Column-wise addition, row-wise addition

In [15]:
import numpy as np

A = np.array([[1,2],[3,4]])
print(A)
print(np.sum(A))  # Compute sum of all elements; prints "10"
print(np.sum(A, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(A, axis=1))  # Compute sum of each row; prints "[3 7]"

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


## Broadcasting in Numpy

- As an example of broadcasting assume, we want to add a vector to all rows of a matrix

In [16]:
# here, we have not use Broadcasting property in numpy
import numpy as np

A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = np.empty_like(A)   # Create an empty matrix with the same shape as A

# Add the vector v to each row of the matrix A with an explicit loop
for i in range(4):
    y[i, :] = A[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 
y = A + vv
print(y)

### We do not need any above steps, with Broadcasting property in numpy the task is easy

In [17]:
import numpy as np

A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(A.shape)
v = np.array([1, 0, 1])

# no need to do A + np.ones((4, 1))*v
A + v

(4, 3)


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

## Reshaping

In [ ]:
B = A.reshape(2, 6)
B

## Array Manipulation in Numpy

- Lets define the following 2D array where the rows are subjects (people) the first column is people weights and the second column is their heights

In [18]:
X = np.array(
[[73.847017017515, 241.893563180437],
 [68.7819040458903, 162.3104725213],
 [74.1101053917849, 212.7408555565],
 [71.7309784033377, 220.042470303077],
 [69.8817958611153, 206.349800623871],
 [67.2530156878065, 152.212155757083],
 [68.7850812516616, 183.927888604031],
 [68.3485155115879, 167.971110489509],
 [67.018949662883, 175.92944039571],
 [63.4564939783664, 156.399676387112]]
)    

In [19]:
# average of each column
np.mean(X, axis=0)

array([ 69.32138568, 187.97774338])

In [20]:
X - np.mean(X, axis=0)

array([[  4.52563134,  53.9158198 ],
       [ -0.53948164, -25.66727086],
       [  4.78871971,  24.76311217],
       [  2.40959272,  32.06472692],
       [  0.56041018,  18.37205724],
       [ -2.06836999, -35.76558762],
       [ -0.53630443,  -4.04985478],
       [ -0.97287017, -20.00663289],
       [ -2.30243602, -12.04830299],
       [ -5.8648917 , -31.57806699]])

## The following is meaningless but mathematically doable

In [21]:
# the average of each row
np.mean(X, axis=1)

array([157.8702901 , 115.54618828, 143.42548047, 145.88672435,
       138.11579824, 109.73258572, 126.35648493, 118.159813  ,
       121.47419503, 109.92808518])

In [22]:
X - np.c_[np.mean(X, axis=1), np.mean(X, axis=1)]

array([[-84.02327308,  84.02327308],
       [-46.76428424,  46.76428424],
       [-69.31537508,  69.31537508],
       [-74.15574595,  74.15574595],
       [-68.23400238,  68.23400238],
       [-42.47957003,  42.47957003],
       [-57.57140368,  57.57140368],
       [-49.81129749,  49.81129749],
       [-54.45524537,  54.45524537],
       [-46.4715912 ,  46.4715912 ]])

## Linear Algebra

- Why we need Linear Algebra

    1- To solve a system of linear equations
    
    2- Most of machine learning models and all most all deep learning models need it

## Matrix-Vector and Matrix-Matrix Multiplication

- On piece of paper, multiply the following matrix-vector:

<img src="matrix_matrix.png" width="300" height="300">

- On piece of paper, multiply the following matrices:

<img src="matrix_vector.png" width="300" height="300">

## Verify your answer in Python using Numpy

In [23]:
A = np.array([[1, 2], [0, 1], [2, 3]])
v = np.array([[2], [6]])
print(A)
print(v)
print(np.dot(A, v))

[[1 2]
 [0 1]
 [2 3]]
[[2]
 [6]]
[[14]
 [ 6]
 [22]]


In [24]:
A = np.array([[1, 2], [0, 1], [2, 3]])
B = np.array([[2, 5], [6, 7]])
print(A)
print(B)
print(np.dot(A, B))

[[1 2]
 [0 1]
 [2 3]]
[[2 5]
 [6 7]]
[[14 19]
 [ 6  7]
 [22 31]]


## Transpose of a Matrix or a Vector 

- In linear algebra, the transpose of a matrix is an operator which switches the row and column indices of the matrix by producing another matrix denoted as Aᵀ

<img src="matrix-transpose.jpg" width="300" height="300">

## Matrix Multiplication (more examples)

In [ ]:
a = np.ones([9, 5])
b = np.ones([5, 3])

np.dot(a, b)

In [ ]:
a = np.ones([2, 2])
b = np.ones([2, 2])
print(np.dot(a, b))
print('This is element-wise multiplication')
print(a*b)
print(np.matmul(a, b))
# The @ operator for multiplication invokes the matmul() function of an array that is used to perform the same multiplication.
print(a@b)

## For high-dimensional arrays, there would be difference between matmul and dot
- https://www.delftstack.com/howto/numpy/numpy-dot-vs-matmul/

## Norm of a vector

- We have different norm, here we mean L2-norm, which measures the distance of a vector from origin (magnitude of a vector)

## Activity: what is the length of the following vector:

- v = [3, 4]

In [7]:
from numpy import linalg as LA
v = np.array([3, 4])
LA.norm(v)

5.0

## Activity: Show that norm of a vector v is the sqrt of np.dot(v,v.T)

In [8]:
v = np.array([3, 4])
np.sqrt(np.dot(v,v.T))

5.0

## Activity: The distance between two vector u and v

<img src="norm.png" width="500" height="500">

In [9]:
u = np.array([1, 1])
v = np.array([2, 2])
r = np.array([3, 8])
print(LA.norm(u - v))
print(LA.norm(u - r))
print(LA.norm(v - r))

1.4142135623730951
7.280109889280518
6.082762530298219


## Other matrix manipulations with numpy

- Trace of a matrix
- Inverse of an squared matrix
- Diagonal elements of a matrix

## Resources:

- numpy cheatsheet: https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

- https://cs231n.github.io/python-numpy-tutorial/

- https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

- http://matrixmultiplication.xyz