# DSCI 521: Methods for analysis and interpretation <br> Chapter 1: Processing numeric data

## Exercises
Note: numberings refer to the main notes.

#### 1.0.2.3 Exercise: Creating a matrix 
Using the above matrix-generation techniques, create a 2x2 identity matrix.

In [1]:
import numpy as np
## code here

#### 1.0.2.5 Exercise: broadcast operations 
Square each element in the matrix `A` without using any loops.

In [2]:
A = [1, 2, 3, 4, 5]
## code here

#### 1.1.2.2 Exercise: vector arithmetic 
Calculate `A` - `B` for the provided vectors, without using a loop.

In [3]:
A = [i for i in range(5)]
B = [-i for i in range(5)]
## code here

#### 1.1.2.5 Exercise: scalar multiplication
Divide each element in the above vector `v` by 4.

In [4]:
v = np.array([9., 2., 4., 8., 1.])
## code here

#### 1.1.2.7 Exercise: pointwise vector multiplication 
Perform pointwise multiplication between `v` divided by 4 which you calculated above, and `u`.

In [5]:
u = np.array([-5., 3.7, 2., 10., 0.])
## code here

#### 1.1.2.9 Exercise: inner products 
Find the dot product of the provided array `z` with `u` and `v`, respectively, from above.

In [6]:
z = np.array([1, 2, 3, 4, 5])

u = np.array([-5., 3.7, 2., 10., 0.])
v = np.array([9., 2., 4., 8., 1.])

## code here

#### 1.1.2.11 Exercise: cosine similarity 
Find the cosine similarity of the vectors `a` and `b`.

In [7]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

## code here

#### 1.1.3.3 Exercise: Matrix indexing 
Print the value in the above matrix `A` located in the bottom-right entry.

In [8]:
A = np.array([
    [ 1,  2,  3],
    [ 4,  5,  6],
    [ 7,  8,  9],
    [10, 11, 12]
])

## code here

#### 1.1.4.2 Exercise: matrix addition 
Using `A` and `B` from above, find the sum `A` + `B` + `A`.

In [9]:
## define a 4-row by 3-column matrix
A = np.array([
    [ 1,  2,  3],
    [ 4,  5,  6],
    [ 7,  8,  9],
    [10, 11, 12]
])

print(A, '\n')

## define another 4-row by 3-column matrix
B = np.array([
    [ 11,  12,  13],
    [ 14,  15,  16],
    [ 17,  18,  19],
    [ 20,  21,  22]
])

print(B, '\n')
## code here

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]] 



#### 1.1.4.4 Exercise: Scalar matrix multiplication
Divide each element in the above matrix `A` by 4.

In [10]:
A = np.array([
    [ 1,  2,  3],
    [ 4,  5,  6],
    [ 7,  8,  9],
    [10, 11, 12]
])

## code here

## Additional In-depth Exercises

### A. Getting to know numpy and word vectors
While we won't begin with text analysis formally until next chapter, we can take some pre-computed data to start exploring language with linear algebraic methods.

#### Main data
The numpy array file in `path = './01-numeric/data/vectors-' + str(dim) + '-.npy'`, which is a `dim = 10` dimensional semantic representation for the words of Mary Shelly's Frankenstein, Or the Modern Prometheus. The object has three linear-algebraic components: $U$, $V$, and $b$ and each has a row-dimension $N$ that represents the vocabulary size. Once loaded these are layed out as:

$$  
\begin{bmatrix} 
v_{1,1} & v_{1,2} & \dots & v_{1,10} \\ 
v_{2,1} & v_{2,2} & \dots & v_{2,10} \\ 
\vdots & \vdots & \ddots & \vdots \\ 
v_{N,1} & v_{N,2} & \dots & v_{N,10} 
\end{bmatrix} 
\begin{bmatrix} 
u_{1,1} & u_{1,2} & \dots & u_{1,10} \\ 
u_{2,1} & u_{2,2} & \dots & u_{2,10} \\ 
\vdots & \vdots & \ddots & \vdots \\ 
u_{N,1} & u_{N,2} & \dots & u_{N,10} 
\end{bmatrix} 
\begin{bmatrix} 
 b_{1} \\ 
 b_{2} \\ 
 \vdots \\ 
 b_{N} 
\end{bmatrix} 
$$

#### A.1 Load a `numpy` matrix with pre-set values from disk.

Load the vectors from disk using `np.load(path)` and slice the resulting object to produce `U`, `V`, and `b` arrays. Report the dimensions of each array to confirm their structure (and the size of the vocabulary).

In [11]:
import numpy as np

dim = 10
## code here

#### A.2 Save the `numpy` matrices with pre-set values from disk.
Then, save these to disk under the paths:

- `./01-numeric/data/U.npy`, 
- `./01-numeric/data/V.npy`, and 
- `./01-numeric/data/b.npy`.

using the `np.save(path, array)` command.

In [12]:
## code here

#### A.3 Load the linked data for the vectors and build the word index
Load `data = json.load(open('./data/vectors-linked_data.json'))` and inspect the resulting object. For now, you'll only have to utilize the dictionary value within it, called `data['counts']`, which is a dictonary, keyed by words, with count-occurrence values (frequencies).

Using `data['counts']`, construct a `word_index` object, which is a dictionary of the form:
```
word_index = {
    w: representation_index,
    ...
}
```

such that `w` is any word string keying `data['counts']` and `representation_index` is the row index for `w` `U`-`V`-`b` representation of `w`. Hint: Python (>3) dictionaries hold keys in the order in which they were originally loaded, i.e., presentated in the json string serialization format. Use this and the fact that the the words were counted in the book's reading order.

In [13]:
import json
## code here

#### A.4 Write a flexible concatenation function
We'll want to conditionally concatenate the different representation components `U`, `V`, and `b`, but will assume that we're always going to use `U`. So write a function called `concatenate(U, V = 0, b = 0)` and stacks as many are non-zero size-by-side (as columns).

[Hint. Use the `np.column_stack()` function!]

In [14]:
## code here

#### A.5 Write a cosine similarity functions that determines the most similar (word) vectors
Use the `concatenate()` function from the previous cell to flexibly stack the different columns. This will allow us to explore how/where the representations stores semantics.

_Accepts_:
- `w`: the target string to measure similarity against
- `U`, `V (= 0)`, `b (= 0)`: the semantic arrays from the representation or integer (null)
- `top (= 0)`: an integer describing the number of 'most similar' words/scores, and
- `v (= 0)`: a `V` (plus `U` and/or `b` dimensional) vector to which to compare to the vectors, instead of the target word.

_Returns_:
- `w_sims`: a sorted list of `top` tuples, of form: `(v, w_v_similarity)`, sortet high to low by `w_v_similarity` (cosine) values between vectors for words `w` and `v`.

Note: vectors must be unit-normed in order to compute these similarities!

In [15]:
## code here

#### A.6 Build an analogy generator
The classic motivation for the utility of word2vec is it's capacity to represent semantic constructs that 'locally' obey liear relationships. The most well known semantic constructs represented are loosely analogies, e.g., across gender, like:
$$
\hat{v}_\text{queen}\approx \frac{1}{3}\left(v_\text{king} - v_\text{man} + v_\text{woman}\right)
$$.

Here, build an analogy generator by writing a function:
- `analogy(positive, negative, word_index, U, V=0, b=0, top=10)`,
which accepts a list of two words called `positive` and a string called `negative` (in addition to the others from __A.4__), computes the above, and (uses this as `v` in the result of __A.4__) to compute the most similar other words in the vocabulary to the specified linear combination.

In [16]:
## code here